# Generated by Django 4.2 on 2026-09-15 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='category',
            new_name='shop_catego_is_acti_b15761_idx',
            old_name='shop_catego_is_acti_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_categor_a79507_idx',
            old_name='shop_produc_catego_idx',
        ),
        migrations.RenameIndex(
            model_name='product',
            new_name='shop_produc_is_acti_ebf53f_idx',
            old_name='shop_produc_active_idx',
        ),
        migrations.RenameIndex(
            model_name='productimage',
            new_name='shop_produc_product_c73091_idx',
            old_name='shop_image_product_idx',
        ),
        migrations.RenameIndex(
            model_name='productvariant',
            new_name='shop_produc_product_27d2af_idx',
            old_name='shop_var_product_idx',
        ),
    ]
