# Generated by Django 4.2 on 2026-09-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_discount_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsize',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=60, verbose_name='اسلاگ'),
        ),
        migrations.AddConstraint(
            model_name='productsize',
            constraint=models.UniqueConstraint(fields=('slug',), name='unique_product_size_slug'),
        ),
    ]
