# Generated by Django 4.2

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0004_alter_productsize_slug_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductComment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("body", models.TextField(max_length=2000, verbose_name="متن نظر")),
                ("rating", models.PositiveSmallIntegerField(blank=True, help_text="اختیاری؛ از ۱ تا ۵ ستاره.", null=True, validators=[models.MinValueValidator(1)], verbose_name="امتیاز")),
                ("status", models.CharField(choices=[("pending", "در انتظار بررسی"), ("approved", "تأییدشده"), ("rejected", "ردشده")], db_index=True, default="pending", max_length=12, verbose_name="وضعیت")),
                ("verified_purchase", models.BooleanField(db_index=True, default=False, verbose_name="خرید تأییدشده")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="زمان ثبت")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="آخرین بروزرسانی")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="comments", to="shop.product", verbose_name="محصول")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="product_comments", to=settings.AUTH_USER_MODEL, verbose_name="کاربر")),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(fields=("product", "status", "-created_at"), name="shop_comment_product_idx"),
                    models.Index(fields=("user", "status", "-created_at"), name="shop_comment_user_idx"),
                ],
            },
        ),
    ]
