# Generated by Django 4.2 on 2026-09-16 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='artwork',
            new_name='customizer__is_acti_9155b3_idx',
            old_name='customizer_artwork_active_idx',
        ),
        migrations.RenameIndex(
            model_name='artworkareaprice',
            new_name='customizer__area_id_79ef14_idx',
            old_name='customizer_price_lookup_idx',
        ),
        migrations.RenameIndex(
            model_name='designdraft',
            new_name='customizer__product_495351_idx',
            old_name='customizer_draft_lookup_idx',
        ),
        migrations.RenameIndex(
            model_name='designerview',
            new_name='customizer__product_ca703a_idx',
            old_name='customizer_view_lookup_idx',
        ),
        migrations.RenameIndex(
            model_name='designlayer',
            new_name='customizer__draft_i_c2cc3a_idx',
            old_name='customizer_layer_lookup_idx',
        ),
        migrations.RenameIndex(
            model_name='printarea',
            new_name='customizer__product_ad75ba_idx',
            old_name='customizer_area_lookup_idx',
        ),
    ]
