# Generated by Django 4.2 on 2026-09-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0002_demo_designer_setup'),
        ('customizer', '0002_rename_customizer_artwork_active_idx_customizer__is_acti_9155b3_idx_and_more'),
    ]

    operations = [
    ]
