# Generated by Django 4.2 on 2026-09-16 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0003_designer_view_3d_model'),
        ('customizer', '0003_merge_20260916_2259'),
    ]

    operations = [
    ]
