# Generated by Django 4.2 on 2026-09-16 20:24

import apps.customizer.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0004_merge_20260916_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designerview',
            name='model_3d',
            field=models.FileField(blank=True, help_text='مدل ترجیحاً GLB باشد و UV mapping مناسب برای چاپ داشته باشد.', null=True, upload_to=apps.customizer.models._model_path, validators=[django.core.validators.FileExtensionValidator(['glb', 'gltf'])], verbose_name='مدل سه\u200cبعدی لباس (GLB/GLTF)'),
        ),
    ]
