# Generated by Django 4.2 on 2026-09-16 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0004_remove_demo_3d_models'),
        ('customizer', '0005_alter_designerview_model_3d'),
    ]

    operations = [
    ]
