# Generated by Django 4.2 on 2026-09-16 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0005_product_3d_asset'),
        ('customizer', '0006_merge_20260917_0009'),
    ]

    operations = [
    ]
