# Generated by Django 4.2 on 2026-09-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0002_artwork_code'),
        ('customizer', '0007_merge_0005_product_3d_asset_0006_merge_20260917_0009'),
    ]

    operations = [
    ]
