# Generated by Django 4.2 on 2026-09-18 20:33

import apps.customizer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0008_merge_20260919_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='code',
            field=models.CharField(db_index=True, default=apps.customizer.models._artwork_code, editable=False, max_length=40, unique=True, verbose_name='کد لیبل'),
        ),
    ]
