# Generated by Django 4.2 on 2026-09-25

import apps.customizer.models
from django.db import migrations, models
import django.db.models.deletion
from django.core.validators import MinValueValidator


class Migration(migrations.Migration):

    dependencies = [
        ("customizer", "0009_alter_artwork_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="designdraft",
            name="base_price",
            field=models.PositiveBigIntegerField(default=1000000, validators=[MinValueValidator(0)], verbose_name="قیمت پایه طراحی"),
        ),
        migrations.AddField(
            model_name="designdraft",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="زمان نهایی شدن"),
        ),
        migrations.AddField(
            model_name="designdraft",
            name="design_code",
            field=models.CharField(
                db_index=True,
                default=None,
                editable=False,
                max_length=40,
                null=True,
                verbose_name="کد طراحی",
            ),
        ),
        migrations.AddField(
            model_name="designdraft",
            name="preview_back",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.customizer.models._design_preview_path,
                verbose_name="پیش‌نمایش دوبعدی پشت",
            ),
        ),
        migrations.AddField(
            model_name="designdraft",
            name="preview_front",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=apps.customizer.models._design_preview_path,
                verbose_name="پیش‌نمایش دوبعدی جلو",
            ),
        ),
        migrations.AddField(
            model_name="designdraft",
            name="shirt_color",
            field=models.CharField(blank=True, max_length=40, verbose_name="رنگ لباس"),
        ),
        migrations.AddField(
            model_name="designlayer",
            name="layer_type",
            field=models.CharField(
                choices=[("artwork", "لیبل"), ("text", "متن")],
                default="artwork",
                max_length=20,
                verbose_name="نوع لایه",
            ),
        ),
        migrations.AddField(
            model_name="designlayer",
            name="side",
            field=models.CharField(
                choices=[("front", "جلو"), ("back", "پشت")],
                default="front",
                max_length=10,
                verbose_name="سمت لباس",
            ),
        ),
        migrations.AddField(
            model_name="designlayer",
            name="text",
            field=models.CharField(blank=True, max_length=120, verbose_name="متن"),
        ),
        migrations.AddField(
            model_name="designlayer",
            name="text_style",
            field=models.JSONField(blank=True, default=dict, verbose_name="استایل متن"),
        ),
        migrations.AlterField(
            model_name="designlayer",
            name="artwork",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="design_layers",
                to="customizer.artwork",
            ),
        ),
    ]