# Generated by Django 4.2 on 2026-09-25 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customizer', '0013_backfill_design_codes'),
        ('customizer', '0014_remove_legacy_design_preview'),
    ]

    operations = [
    ]
