# Generated by Django 4.2
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.core.validators
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("shop", "0003_product_discount_fields"),
        ("users", "0005_rename_users_address_user_default_idx_users_addre_user_id_194804_idx_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cart",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("session_key", models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ("status", models.CharField(choices=[("active", "فعال"), ("converted", "تبدیل‌شده به سفارش"), ("abandoned", "رهاشده")], db_index=True, default="active", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name="carts", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-updated_at",)},
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("uuid", models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ("number", models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ("status", models.CharField(choices=[("pending", "در انتظار پرداخت"), ("paid", "پرداخت‌شده"), ("processing", "در حال آماده‌سازی"), ("shipped", "ارسال‌شده"), ("delivered", "تحویل‌شده"), ("cancelled", "لغوشده"), ("refunded", "مرجوع وجه‌شده")], db_index=True, default="pending", max_length=20)),
                ("payment_status", models.CharField(choices=[("unpaid", "پرداخت نشده"), ("pending", "در انتظار پرداخت"), ("paid", "موفق"), ("failed", "ناموفق"), ("refunded", "مرجوع")], db_index=True, default="unpaid", max_length=20)),
                ("shipping_status", models.CharField(choices=[("pending", "در انتظار ارسال"), ("preparing", "در حال آماده‌سازی"), ("shipped", "ارسال‌شده"), ("delivered", "تحویل‌شده"), ("returned", "مرجوع‌شده")], db_index=True, default="pending", max_length=20)),
                ("shipping_title", models.CharField(max_length=100)),
                ("shipping_recipient", models.CharField(blank=True, max_length=200)),
                ("shipping_phone", models.CharField(max_length=20)),
                ("shipping_province", models.CharField(max_length=120)),
                ("shipping_city", models.CharField(max_length=120)),
                ("shipping_postal_code", models.CharField(max_length=10)),
                ("shipping_address", models.TextField()),
                ("subtotal", models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ("discount_amount", models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ("shipping_amount", models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ("total_amount", models.PositiveBigIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ("currency", models.CharField(default="IRT", max_length=3)),
                ("payment_reference", models.CharField(blank=True, db_index=True, max_length=120)),
                ("customer_note", models.TextField(blank=True)),
                ("admin_note", models.TextField(blank=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("shipped_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="orders", to=settings.AUTH_USER_MODEL)),
            ],
            options={"ordering": ("-created_at",)},
        ),
        migrations.CreateModel(
            name="CartItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("quantity", models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("cart", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="orders.cart")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="cart_items", to="shop.product")),
                ("variant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="cart_items", to="shop.productvariant")),
            ],
            options={"ordering": ("added_at", "id")},
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("product_name", models.CharField(max_length=200)),
                ("variant_sku", models.CharField(blank=True, max_length=80)),
                ("color_name", models.CharField(blank=True, max_length=80)),
                ("size_name", models.CharField(blank=True, max_length=40)),
                ("unit_price", models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ("compare_at_price", models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ("quantity", models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ("line_total", models.PositiveBigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ("order", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="items", to="orders.order")),
                ("product", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="order_items", to="shop.product")),
                ("variant", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="order_items", to="shop.productvariant")),
            ],
            options={"ordering": ("id",)},
        ),
        migrations.AddIndex(model_name="cart", index=models.Index(fields=["user", "status", "updated_at"], name="orders_cart_user_id_4c7e0d_idx")),
        migrations.AddIndex(model_name="cart", index=models.Index(fields=["session_key", "status"], name="orders_cart_sessio_9c8b9b_idx")),
        migrations.AddIndex(model_name="cartitem", index=models.Index(fields=["cart", "product"], name="orders_cart_cart_id_6b6e3d_idx")),
        migrations.AddIndex(model_name="cartitem", index=models.Index(fields=["cart", "variant"], name="orders_cart_cart_id_2d9e1b_idx")),
        migrations.AddIndex(model_name="order", index=models.Index(fields=["user", "-created_at"], name="orders_orde_user_id_8b4d8f_idx")),
        migrations.AddIndex(model_name="order", index=models.Index(fields=["status", "-created_at"], name="orders_orde_status_1c5b74_idx")),
        migrations.AddIndex(model_name="order", index=models.Index(fields=["payment_status", "-created_at"], name="orders_orde_paymen_75c1a5_idx")),
        migrations.AddIndex(model_name="orderitem", index=models.Index(fields=["order", "product"], name="orders_orde_order_i_1e8a0f_idx")),
        migrations.AddConstraint(model_name="cart", constraint=models.UniqueConstraint(condition=models.Q(("user__isnull", False), ("status", "active")), fields=("user",), name="unique_active_cart_per_user")),
        migrations.AddConstraint(model_name="cart", constraint=models.UniqueConstraint(condition=models.Q(("session_key__isnull", False), ("user__isnull", True), ("status", "active")), fields=("session_key",), name="unique_active_guest_cart_per_session")),
        migrations.AddConstraint(model_name="cartitem", constraint=models.UniqueConstraint(condition=models.Q(("variant__isnull", False)), fields=("cart", "variant"), name="unique_cart_variant_item")),
        migrations.AddConstraint(model_name="cartitem", constraint=models.UniqueConstraint(condition=models.Q(("variant__isnull", True)), fields=("cart", "product"), name="unique_cart_product_item")),
        migrations.AddConstraint(model_name="cartitem", constraint=models.CheckConstraint(check=models.Q(("quantity__gt", 0)), name="cart_item_quantity_gt_zero")),
        migrations.AddConstraint(model_name="orderitem", constraint=models.CheckConstraint(check=models.Q(("quantity__gt", 0)), name="order_item_quantity_gt_zero")),
    ]
