# Generated by Django 4.2 on 2026-09-16 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_active_cart_per_user',
        ),
        migrations.RemoveConstraint(
            model_name='cart',
            name='unique_active_guest_cart_per_session',
        ),
        migrations.RenameIndex(
            model_name='cart',
            new_name='orders_cart_user_id_416bbf_idx',
            old_name='orders_cart_user_id_4c7e0d_idx',
        ),
        migrations.RenameIndex(
            model_name='cart',
            new_name='orders_cart_session_25eb61_idx',
            old_name='orders_cart_sessio_9c8b9b_idx',
        ),
        migrations.RenameIndex(
            model_name='cartitem',
            new_name='orders_cart_cart_id_cb3fba_idx',
            old_name='orders_cart_cart_id_6b6e3d_idx',
        ),
        migrations.RenameIndex(
            model_name='cartitem',
            new_name='orders_cart_cart_id_02c352_idx',
            old_name='orders_cart_cart_id_2d9e1b_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_user_id_0ae59f_idx',
            old_name='orders_orde_user_id_8b4d8f_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_status_079368_idx',
            old_name='orders_orde_status_1c5b74_idx',
        ),
        migrations.RenameIndex(
            model_name='order',
            new_name='orders_orde_payment_8bdf8b_idx',
            old_name='orders_orde_paymen_75c1a5_idx',
        ),
        migrations.RenameIndex(
            model_name='orderitem',
            new_name='orders_orde_order_i_52f79a_idx',
            old_name='orders_orde_order_i_1e8a0f_idx',
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'active'), ('user__isnull', False)), fields=('user',), name='unique_active_cart_per_user'),
        ),
        migrations.AddConstraint(
            model_name='cart',
            constraint=models.UniqueConstraint(condition=models.Q(('session_key__isnull', False), ('status', 'active'), ('user__isnull', True)), fields=('session_key',), name='unique_active_guest_cart_per_session'),
        ),
    ]
