# Generated by Django 4.2 on 2026-09-25

from django.db import migrations, models
import django.db.models.deletion
from django.db.models import Q


class Migration(migrations.Migration):

    dependencies = [
        ("customizer", "0010_phase2_design_schema"),
        ("orders", "0002_remove_cart_unique_active_cart_per_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="custom_design",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cart_items",
                to="customizer.designdraft",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="unique_cart_variant_item",
        ),
        migrations.RemoveConstraint(
            model_name="cartitem",
            name="unique_cart_product_item",
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=Q(custom_design__isnull=True, variant__isnull=False),
                fields=("cart", "variant"),
                name="unique_cart_variant_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=Q(custom_design__isnull=True, variant__isnull=True),
                fields=("cart", "product"),
                name="unique_cart_product_item",
            ),
        ),
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.UniqueConstraint(
                condition=Q(custom_design__isnull=False),
                fields=("cart", "custom_design"),
                name="unique_cart_custom_design_item",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="custom_design",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_items",
                to="customizer.designdraft",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="custom_design_code",
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="custom_design_snapshot",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
