# Generated by Django 4.2 on 2026-09-18 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saved', '0001_initial'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='favoriteproduct',
            new_name='saved_favor_user_id_5d9438_idx',
            old_name='saved_favor_user_id_8d8f4d_idx',
        ),
        migrations.RenameIndex(
            model_name='savedproduct',
            new_name='saved_saved_user_id_1df36f_idx',
            old_name='saved_save_user_id_2c4b3d_idx',
        ),
    ]
