# Generated by Django 4.2 on 2024-03-17 20:20

from django.db import migrations


with open("apps/users/data/provinces.sql", encoding="utf8") as f:
    provinces_sql = f.read()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(provinces_sql)
    ]