# Generated by Django 4.2 on 2026-09-16 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_data_integrity"),
        ("users", "0003_add_cities_data"),
    ]

    operations = []
