# Generated by Django 4.2 on 2026-09-16 01:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_merge_0002_user_data_integrity_0003_add_cities_data'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='address',
            new_name='users_addre_user_id_194804_idx',
            old_name='users_address_user_default_idx',
        ),
        migrations.RenameIndex(
            model_name='otp',
            new_name='users_otp_phone_47c136_idx',
            old_name='users_otp_verify_idx',
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message='کد پستی باید دقیقاً ۱۰ رقم باشد.', regex='^\\d{10}$')], verbose_name='کد پستی'),
        ),
    ]
