# Generated by Django 4.2 on 2026-09-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_address_account_list_index'),
        ('users', '0005_rename_users_address_user_default_idx_users_addre_user_id_194804_idx_and_more'),
    ]

    operations = [
    ]
