# Generated by Django 4.2 on 2026-09-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_users_address_user_default_idx_users_addre_user_id_194804_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='users_addre_user_id_194804_idx',
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['user', '-is_default', '-id'], name='users_address_account_list_idx'),
        ),
    ]
