# Generated by Django 4.2 on 2026-09-23 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_merge_20260923_1236'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='address',
            name='users_addre_user_id_194804_idx',
        ),
    ]
